// ── Pre-populated EPA Master List ──
// Royal College Anaesthesiology CBD — Version 2
// All 4 stages, pre-populated with names, codes, targets, and stage assignments

const EPA_MASTER = [
  // ── Transition to Discipline ──
  { code: 'D1', stage: 'Transition to Discipline', target: 3,
    name: 'Performing preoperative assessments for healthy adult patients who will be undergoing a non-complex scheduled surgical procedure' },
  { code: 'D2', stage: 'Transition to Discipline', target: 3,
    name: 'Monitoring adult patients undergoing non-complex surgical procedures, under general or regional anesthesia' },
  { code: 'D3', stage: 'Transition to Discipline', target: 3,
    name: 'Performing the postoperative transfer of care of healthy adult patients following a non-complex surgical procedure, including postoperative orders' },

  // ── Foundations of Discipline ──
  { code: 'F1', stage: 'Foundations of Discipline', target: 8,
    name: 'Using the anesthetic assessment to generate the anesthetic considerations and management plan including postoperative disposition, and obtaining informed consent, for non-complex patients and non-complex surgery' },
  { code: 'F2', stage: 'Foundations of Discipline', target: 20,
    name: 'Providing perioperative anesthetic management for non-complex cases in adult patients' },
  { code: 'F3', stage: 'Foundations of Discipline', target: 20,
    name: 'Performing the non-airway basic procedures of Anesthesiology' },
  { code: 'F4', stage: 'Foundations of Discipline', target: 5,
    name: 'Identifying patients presenting with an anticipated difficult airway and preparing for management options' },
  { code: 'F5', stage: 'Foundations of Discipline', target: 8,
    name: 'Managing and coordinating patient positioning during anesthesia care and preventing and recognizing related complications' },
  { code: 'F6', stage: 'Foundations of Discipline', target: 6,
    name: 'Anticipating, preventing and managing common or expected intraoperative events and physiologic changes during non-complex cases' },
  { code: 'F7', stage: 'Foundations of Discipline', target: 1,
    name: 'Assessing the indications for transfusion of blood products and managing side effects and complications' },
  { code: 'F8', stage: 'Foundations of Discipline', target: 8,
    name: 'Diagnosing and managing common issues in the post-anesthesia care unit (PACU), or the surgical ward' },
  { code: 'F9', stage: 'Foundations of Discipline', target: 3,
    name: 'Initiating resuscitation and diagnosis of patients with life-threatening conditions in a time-appropriate manner' },
  { code: 'F10', stage: 'Foundations of Discipline', target: 8,
    name: 'Assessing, diagnosing and managing patients with common medical or surgical presentations in acute care settings, and advancing their care plans' },
  { code: 'F11', stage: 'Foundations of Discipline', target: 3,
    name: 'Assessing pregnant patients and providing routine obstetric care or initial medical management for acute medical, surgical or obstetric conditions' },
  { code: 'F12', stage: 'Foundations of Discipline', target: 13,
    name: 'Assessing and providing labour analgesia for healthy parturients with an uncomplicated pregnancy, including the management of common complications of labour analgesia' },
  { code: 'F13', stage: 'Foundations of Discipline', target: 5,
    name: 'Providing anesthesia for patients undergoing non-complex cesarean section' },
  { code: 'F14', stage: 'Foundations of Discipline', target: 3,
    name: 'Providing perioperative anesthetic management for non-complex cases in pediatric patients' },
  { code: 'F15', stage: 'Foundations of Discipline', target: 3,
    name: 'Managing pediatric patients with common postoperative complications in the post anesthesia care unit or ward' },
  { code: 'F16', stage: 'Foundations of Discipline', target: 4,
    name: 'Assessing and initiating management for pediatric patients with common medical conditions' },

  // ── Core Discipline ──
  { code: 'C1', stage: 'Core Discipline', target: 10,
    name: 'Using the anesthetic assessment to generate the anesthetic considerations and management plan, including prioritization and optimization, for patients with complex medical diseases or complex surgeries' },
  { code: 'C2', stage: 'Core Discipline', target: 5,
    name: 'Providing anesthetic management for patients with defined critical illness' },
  { code: 'C3', stage: 'Core Discipline', target: 6,
    name: 'Providing perioperative anesthetic management for patients with significant cardiac disease' },
  { code: 'C4', stage: 'Core Discipline', target: 6,
    name: 'Managing patients presenting with a difficult airway, including developing plans for extubation' },
  { code: 'C5', stage: 'Core Discipline', target: 6,
    name: 'Initiating and leading resuscitation for unstable patients in the perioperative period' },
  { code: 'C6', stage: 'Core Discipline', target: 6,
    name: 'Demonstrating required skills in POCUS (point of care ultrasound) to answer a clinical question' },
  { code: 'C7', stage: 'Core Discipline', target: 10,
    name: 'Providing peripartum anesthetic management for high-risk parturients' },
  { code: 'C8', stage: 'Core Discipline', target: 2,
    name: 'Initiating resuscitation and providing anesthetic management for unstable parturients' },
  { code: 'C9', stage: 'Core Discipline', target: 5,
    name: 'Assessing, investigating, optimizing and formulating anesthetic plans for more complex pediatric cases' },
  { code: 'C10', stage: 'Core Discipline', target: 5,
    name: 'Providing perioperative anesthetic management for pediatric patients with more complex cases' },
  { code: 'C11', stage: 'Core Discipline', target: 10,
    name: 'Providing perioperative anesthetic management incorporating a peripheral nerve block technique' },
  { code: 'C12', stage: 'Core Discipline', target: 5,
    name: 'Diagnosing and providing management for patients with complications of regional anesthesia' },
  { code: 'C13', stage: 'Core Discipline', target: 3,
    name: 'Providing anesthetic management for patients undergoing procedures outside the usual environment of the operating room' },
  { code: 'C14', stage: 'Core Discipline', target: 5,
    name: 'Providing perioperative management for patients requiring airway diagnostic and therapeutic procedures' },
  { code: 'C15', stage: 'Core Discipline', target: 6,
    name: 'Providing perioperative anesthetic management for patients undergoing vascular surgery' },
  { code: 'C16', stage: 'Core Discipline', target: 6,
    name: 'Providing perioperative anesthetic management for patients undergoing spinal procedures' },
  { code: 'C17', stage: 'Core Discipline', target: 8,
    name: 'Providing perioperative anesthetic management for patients undergoing intracranial procedures' },
  { code: 'C18', stage: 'Core Discipline', target: 8,
    name: 'Providing perioperative anesthetic management for patients undergoing thoracic surgery' },
  { code: 'C19', stage: 'Core Discipline', target: 3,
    name: 'Assessing and providing comprehensive multi-modal management for patients with complex acute pain' },
  { code: 'C20', stage: 'Core Discipline', target: 4,
    name: 'Assessing, diagnosing and formulating management options for patients with common chronic pain disorders' },
  { code: 'C21', stage: 'Core Discipline', target: 7,
    name: 'Providing comprehensive ongoing management of critically ill patients in an intensive care setting' },
  { code: 'C22', stage: 'Core Discipline', target: 7,
    name: 'Initiating and leading resuscitation for unstable patients, outside of the operating room or PACU' },
  { code: 'C23', stage: 'Core Discipline', target: 3,
    name: 'Managing goals of care discussions with patients and families, including perioperative care plans' },
  { code: 'C24', stage: 'Core Discipline', target: 1,
    name: 'Providing care for patients who have experienced a patient safety incident' },
  { code: 'C25', stage: 'Core Discipline', target: 1,
    name: 'Recognizing and managing ethical dilemmas that arise in the course of patient care' },

  // ── Transition to Practice ──
  { code: 'P1', stage: 'Transition to Practice', target: 3,
    name: 'Managing all aspects of care for patients presenting to a preoperative clinic' },
  { code: 'P2', stage: 'Transition to Practice', target: 10,
    name: 'Managing all aspects of anesthesia care for a scheduled day list' },
  { code: 'P3', stage: 'Transition to Practice', target: 5,
    name: 'Providing anesthesia services for an on-call period' },
  { code: 'P4', stage: 'Transition to Practice', target: 5,
    name: 'Managing all aspects of care for obstetrical anesthesia services' },
  { code: 'P5', stage: 'Transition to Practice', target: null,
    name: 'Developing an academic portfolio' },
];

// Stage color mapping
const STAGE_COLORS = {
  'Transition to Discipline': '#E67E22',
  'Foundations of Discipline': '#0F6E56',
  'Core Discipline': '#6B7FD8',
  'Transition to Practice': '#C75450',
};

// Which EPAs are prioritized for a given rotation (rotation name → array of EPA codes)
const ROTATION_EPA_MAP = {
  'Cardiac': ['C3', 'C5', 'C6', 'F2', 'F6', 'F7', 'C1'],
  'ICU': ['C21', 'C22', 'F9', 'C5', 'C23', 'C24'],
  'OB': ['F11', 'F12', 'F13', 'C7', 'C8'],
  'Paeds': ['F14', 'F15', 'F16', 'C9', 'C10'],
  'Regional': ['C11', 'C12', 'F3', 'F4'],
  'Neuro': ['C17', 'C4', 'C14'],
  'Thoracic': ['C18', 'C2', 'C3'],
  'Vascular': ['C15', 'C2', 'C1'],
  'Pain': ['C19', 'C20'],
  'General': ['D1', 'D2', 'D3', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F8'],
  'Emergency': ['F9', 'F10', 'C5', 'C22'],
  'Transition to Practice': ['P1', 'P2', 'P3', 'P4', 'P5'],
};
